services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "8765:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - andy-angular-volume:/opt/keycloak/data
    command: start-dev --import-realm
    networks:
      - andy-angular-network
    restart: always

networks:
  andy-angular-network:
    driver: bridge
volumes:
  andy-angular-volume:
    driver: local
